import React from 'react';

const PrivacyPolicyContent = () => (
  <>
    <p className="text-xs md:text-sm font-bold text-slate-500 mb-10 md:mb-14">
      Version 1.0. Last Updated: [INSERT DATE].
    </p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Introduction and Scope</h3>
    <p className="mb-6"><strong>Data Controller:</strong> Amplify Give LLC, 7901 4th St N, Ste 32498, St. Petersburg, FL 33702, email: privacy@amplifygive.com. For questions about your data, contact privacy@amplifygive.com.</p>
    <p className="mb-6">The Privacy Policy for Amplify governs the collection, use, retention, and sharing of personal data across our digital platform, recurring charitable pledge systems, and sweepstakes administration services. This policy applies to all visitors, registered donors, Alternate Means of Entry (AMOE) sweepstakes participants, and platform users. The Services are offered only to residents of the United States, and this policy addresses U.S. state consumer privacy laws that may apply to our practices, including the California Privacy Rights Act (CPRA), the Virginia Consumer Data Protection Act (VCDPA), and the Colorado Privacy Act (CPA).</p>
    <p className="mb-6">By utilizing the Amplify platform to make a Contribution or enter a promotional sweepstakes, you acknowledge the data practices described within this document. This policy details the categories of personal information we collect, the specific business purposes for that collection, and the third parties with whom your data may be shared to facilitate charitable regranting and legal sweepstakes compliance.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Categories of Personal Information Collected</h3>
    <p className="mb-6">Amplify collects the following categories of personal information from its users, as defined by applicable state privacy laws. We limit the information we collect to what is reasonably necessary and proportionate to our disclosed purposes.</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>Identifiers:</strong> We collect real names, postal addresses, unique personal identifiers, online identifiers, Internet Protocol (IP) addresses, email addresses, and date of birth (collected at checkout solely to confirm you meet the minimum age to participate; we do not store your date of birth, only a record that the age check was completed, consisting of the date and time of the check and your age in years at that time). Date of birth is also provided on AMOE postcards and winner documentation, which are retained as described below. This information is sourced directly from you during account creation, donation checkout, or Alternate Means of Entry (AMOE) sweepstakes participation.</li>
      <li className="pl-2"><strong>Commercial Information:</strong> We maintain records of your charitable pledges, including donation amounts, transaction histories, the organizations you vote for, and any optional notes or memos you provide alongside your pledge.</li>
      <li className="pl-2"><strong>Internet or Electronic Network Activity Information:</strong> We use Google Analytics and Microsoft Clarity for analytics, platform security, fraud prevention, and understanding how visitors use the Services. Microsoft Clarity provides behavioral analytics, including heatmaps and reconstructed session replays based on interactions such as clicks, scrolling, cursor movement, and page activity. Sensitive form content is configured to be masked.</li>
      <li className="pl-2"><strong>Geolocation Data:</strong> We capture geographic data derived from your IP address to detect fraudulent activity and to ensure that you reside in a jurisdiction where participation in our specific sweepstakes promotions is legally permissible.</li>
      <li className="pl-2"><strong>Financial Information:</strong> You provide payment card details to initiate recurring pledges through our PCI Level 1 compliant payment processor, Stripe. Amplify is the merchant of record for your Contribution charge and uses Stripe Connect to transfer your Contribution to the Foundation; see "Data Security and Breach Notification" below for how card data is protected, and the Official Rules and Terms of Use for details of that transfer.</li>
      <li className="pl-2"><strong>Ambassador / Referral Data:</strong> If you receive payments as a referrer or ambassador, we will require tax information for reporting and may issue 1099 forms as required by law.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Use and Disclosure of Sensitive Personal Information</h3>
    <p className="mb-6">In the administration of our monthly appreciation sweepstakes, Amplify awards prizes of substantial value. In strict accordance with United States federal tax laws, any participant who wins a prize of eligible value is required to be issued an IRS Form 1099-MISC.</p>
    <p className="mb-6">Winners will be required to provide tax documentation (W-9) and complete identity verification. Required prize reporting information (name, address, taxpayer ID, prize value) will be shared with tax authorities and our payment processor. Please note that under the One Big Beautiful Bill Act, the federal Form 1099-MISC reporting threshold for prizes awarded after December 31, 2025, has increased to $2,000 (subject to future IRS inflation adjustments).</p>
    <p className="mb-6">Under the California Privacy Rights Act (CPRA) and allied state laws, an SSN constitutes Sensitive Personal Information (SPI). Amplify collects and processes this SPI exclusively for the business purpose of satisfying federal and state tax reporting obligations and verifying the identity of prize winners to prevent financial fraud. We do not use, sell, or share Sensitive Personal Information for any secondary purposes, including marketing or behavioral profiling. You have the right to limit the use of your sensitive data beyond what is necessary for these legally mandated business operations. To exercise this right, email privacy@amplifygive.com with the subject "Limit Use of Sensitive Personal Information."</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">How We Share Your Information with Third Parties</h3>
    <p className="mb-6">Amplify operates as an intermediary to facilitate your charitable impact and administer appreciation sweepstakes. We do not sell, rent, or lease your personal data to third-party data brokers. We share your information strictly in the following operational contexts:</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>The Foundation:</strong> Contributions are remitted to [DAF SPONSOR LEGAL NAME] (the "Foundation"), a Section 501(c)(3) sponsoring organization that maintains charitable funds. By making a Contribution, you consent that Amplify may share your name, email, and Contribution amount with the Foundation for receipting and grant administration. The Foundation may contact you directly regarding your Contribution and to provide tax documentation where applicable. We do not share your name, email, or other personal information with any Supported Organization you vote for; grants are made by the Foundation, based on Amplify's aggregated Tier-level recommendation, without identifying any individual member.</li>
      <li className="pl-2"><strong>Payment Processors:</strong> We share transaction data with Stripe, our payment processor, to charge and process your Contribution. See "Data Security and Breach Notification" below for how card data is handled.</li>
      <li className="pl-2"><strong>Infrastructure and Communication Providers:</strong> We share necessary data elements with vetted third-party service providers who help operate the Services, including Stripe (payment processing), Supabase (application backend and data storage), Vercel (website hosting), Resend (transactional and marketing email), Formspree (contact form submissions), Google Analytics and Microsoft Clarity (website analytics), and the Foundation.</li>
      <li className="pl-2"><strong>Legal and Safety Obligations:</strong> We may disclose personal information to external entities, including law enforcement or state and federal tax authorities, when such disclosure is legally necessary to comply with subpoenas, investigate potential violations of civil or criminal law, or protect the integrity of our platform against fraud.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Sweepstakes Transparency and Publicity Rights</h3>
    <p className="mb-6">By participating in the monthly appreciation sweepstakes administered by Amplify, you acknowledge that specific data processing practices are governed by state and federal sweepstakes laws, which may supersede certain general privacy rights regarding data deletion.</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>AMOE Scans and Retention:</strong> Alternate Method of Entry (AMOE) submissions (handwritten postcards and envelope postmarks) are scanned and retained for audit purposes for up to 3 years. Scanned images are stored encrypted; physical envelopes are stored in locked facilities accessible only to authorized staff. AMOE data will be used for eligibility verification, fraud detection, and regulatory audit upon request.</li>
      <li className="pl-2"><strong>Winners List Mandate:</strong> To demonstrate the fairness and legality of our promotions, state laws require Amplify to maintain a ledger of major prize winners. We retain and disclose winner information to regulators and make winner information available to the public only to the extent required by the Official Rules or applicable law; the categories of information and retention period vary by jurisdiction. We will also share required personal data with tax authorities and our payment processor to comply with reporting obligations. While you hold the right to request the deletion of your personal data under the CPRA, Amplify is legally obligated to retain and disclose this specific Winner List information to comply with state regulatory audits and legal obligations.</li>
      <li className="pl-2"><strong>Publicity Release:</strong> Putting a name and face to our winning entrants helps build trust in our community. If you are selected as a winner, we may request that you execute the Affidavit of Eligibility, Liability Release, and Publicity Release. By signing this release, you grant Amplify permission to use your name, likeness, and details of your win for advertising and promotional purposes without further compensation, unless prohibited by law.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Your State Privacy Rights and How to Exercise Them</h3>
    <p className="mb-6">Depending on your state of residence, including under the California Privacy Rights Act (CPRA), you are granted specific legal rights regarding your personal data. Amplify respects these rights for all U.S. users. Response deadlines for the rights below are set by, and may vary under, the law of your state of residence:</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>The Right to Know and Access:</strong> You have the right to request that we disclose the specific pieces of personal information we have collected about you, the sources of that information, our business purposes for collecting it, and the categories of third parties with whom it is shared.</li>
      <li className="pl-2"><strong>The Right to Data Portability:</strong> You have the right to receive a copy of your personal information in a portable, readily usable format, where required by applicable law.</li>
      <li className="pl-2"><strong>The Right to Opt Out of Sale, Sharing, Targeted Advertising, and Profiling:</strong> Amplify does not sell or share your personal information for cross-context behavioral advertising and does not engage in profiling that produces legal or similarly significant effects; see "Cookies and Tracking" below for how to opt out of analytics tracking.</li>
      <li className="pl-2"><strong>Authorized Agents:</strong> You may designate an authorized agent to submit a request on your behalf. We will require the agent to provide written proof that you authorized them to act on your behalf, and we may still require you to directly verify your own identity or directly confirm to us that you authorized the agent to make the request.</li>
      <li className="pl-2"><strong>Data Retention and Deletion:</strong> General account data is retained for 7 years. AMOE scans and audit data are retained for 3 years. Payment receipts are retained for 7 years. To request deletion, email privacy@amplifygive.com with the subject "Data Deletion Request." We may deny your deletion request if retaining the information is legally necessary for us to fulfill the terms of a charitable pledge, comply with IRS tax reporting, or comply with state laws mandating the retention of sweepstakes records.</li>
      <li className="pl-2"><strong>Cookies and Tracking (Do Not Sell or Share My Information):</strong> Amplify does not sell your personal information for money. We use Google Analytics and Microsoft Clarity for analytics purposes only; Amplify does not use Google Analytics or Microsoft Clarity for targeted advertising or to build cross-context advertising profiles. Google's cross-device ad signal linking is disabled in our account settings, and neither tool is linked to any advertising account. To opt out of analytics tracking, email privacy@amplifygive.com with the subject "Opt Out of Analytics Tracking." We do not currently operate a cookie consent banner. We do automatically detect and honor the Global Privacy Control (GPC) signal: when your browser sends it, our analytics tools (Google Analytics and Microsoft Clarity) are not loaded for your visit.</li>
      <li className="pl-2"><strong>Marketing Email Opt-Out:</strong> Every marketing email includes a functioning unsubscribe link, which is the fastest way to stop marketing emails. Transactional messages about your account and Contributions are not marketing and will continue while your account is active.</li>
      <li className="pl-2"><strong>The Right to Correction and Non-Discrimination:</strong> You have the right to correct inaccurate personal data. Amplify will never deny you services or charge you different prices because you exercised your privacy rights.</li>
      <li className="pl-2"><strong>Right to Appeal:</strong> If we decline to act on a request to know, delete, or correct your personal data, you may appeal that decision by emailing privacy@amplifygive.com with the subject "Privacy Appeal." We will respond to your appeal within forty-five (45) days, extendable by up to sixty (60) additional days where reasonably necessary. If we deny your appeal, we will explain our reasons in writing and, for Virginia and Colorado residents, provide information on how to contact your state Attorney General to submit a complaint.</li>
    </ul>
    <p className="mb-6"><strong>Contact and Complaint Route:</strong> For verifiable consumer requests, or to escalate complaints, please email our privacy officer at privacy@amplifygive.com. If unresolved, you may escalate to legal@amplifygive.com.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Data Security and Breach Notification</h3>
    <p className="mb-6">Amplify takes the security of your personal, financial, and tax information with the utmost seriousness. Payment card data is processed by Stripe, and Amplify does not store full card numbers. We use encryption in transit and at rest and restrict access to a need-to-know basis.</p>
    <p className="mb-6">While we employ rigorous security measures, no digital platform is entirely invulnerable. In the event of a security incident that compromises your unencrypted personal information, Amplify maintains a comprehensive breach response protocol. We will notify affected users without undue delay and in accordance with applicable law, and we will act rapidly to secure our systems and investigate the scope of the incident.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Children's Privacy</h3>
    <p className="mb-6">The services provided by Amplify, including our charitable pledge systems and monthly appreciation sweepstakes, are strictly limited to adults who have reached the age of majority in their jurisdiction (18 in most states, 19 in Alabama and Nebraska, and 21 in Mississippi). We do not knowingly solicit, collect, or maintain personal information from anyone under the age of legal majority, nor do we permit them to utilize our platform. If you are a parent or guardian and discover that your minor child has provided us with personal information, please contact us immediately at privacy@amplifygive.com. Upon verification, we will take immediate steps to systematically delete that information from our databases and terminate the associated account.</p>
  </>
);

export default PrivacyPolicyContent;
