import React from 'react';

const PrivacyPolicyContent = () => (
  <>
    <p className="mb-6"><strong>Data Controller:</strong> Amplify Ltd., [address], email: privacy@amplify.org. For questions about your data, contact privacy@amplify.org.</p>
    <p className="mb-6">The Privacy Policy for Amplify governs the collection, use, retention, and sharing of personal data across our digital platform, recurring charitable pledge systems, and sweepstakes administration services. This policy applies to all visitors, registered donors, Alternate Means of Entry (AMOE) sweepstakes participants, and platform users. Amplify adopts a comprehensive compliance posture designed to satisfy the rigorous requirements of the California Privacy Rights Act (CPRA), the Virginia Consumer Data Protection Act (VCDPA), the Colorado Privacy Act (CPA), and all allied state consumer privacy frameworks taking effect through 2025 and 2026.</p>
    <p className="mb-6">Residents of California hold specific CCPA rights, and residents of the EEA hold GDPR rights regarding access, deletion, and portability. Data may transfer to the U.S. and other countries; we use standard contractual clauses where required. By utilizing the Amplify platform to initiate a charitable pledge or enter a promotional sweepstakes, you acknowledge the data practices described within this document. We are committed to transparency, and this policy explicitly details the categories of personal information we collect, the specific business purposes for that collection, and the strictly vetted third parties with whom your data may be shared to facilitate charitable regranting and legal sweepstakes compliance.</p>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Categories of Personal Information Collected</h3>
    <p className="mb-6">In the preceding twelve months, Amplify has collected the following categories of personal information from its users, as defined by applicable state privacy laws. We limit the information we collect to what is strictly necessary for our mission and sweepstakes administration.</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>Identifiers:</strong> We collect real names, postal addresses, unique personal identifiers, online identifiers, Internet Protocol (IP) addresses, and email addresses. This information is sourced directly from you during account creation, donation checkout, or Alternate Means of Entry (AMOE) sweepstakes participation.</li>
      <li className="pl-2"><strong>Commercial Information:</strong> We maintain records of your charitable pledges, including donation amounts, transaction histories, selected recipient charities, and any optional notes or memos you provide alongside your pledge.</li>
      <li className="pl-2"><strong>Internet or Electronic Network Activity Information:</strong> We collect data regarding your interaction with our platform via cookies and web beacons. This includes browsing history, search history, and page interaction data, utilized strictly to maintain platform security, prevent fraudulent sweepstakes entries, and optimize user experience.</li>
      <li className="pl-2"><strong>Geolocation Data:</strong> We capture geographic data derived from your IP address to detect fraudulent activity and to ensure that you reside in a jurisdiction where participation in our specific sweepstakes promotions is legally permissible.</li>
      <li className="pl-2"><strong>Financial Information:</strong> While you provide payment card details to initiate recurring pledges, Amplify never directly sees, processes, or stores raw payment card information on our servers. This data is transmitted directly via end-to-end encryption to our PCI Level 1 compliant payment processors.</li>
      <li className="pl-2"><strong>Referral Data:</strong> If you receive payments as a referrer, we will require tax information for reporting and may issue 1099 forms as required by law.</li>
      <li className="pl-2"><strong>Processing vs. Donation Distinction:</strong> Payments processed by Change into the DAF may entitle you to a tax receipt issued by Change. Payments processed by Amplify as entry purchases are non-deductible and are recorded as purchases/fees on Amplify receipts. See Official Rules for full financial flow.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Use and Disclosure of Sensitive Personal Information</h3>
    <p className="mb-6">In the administration of our monthly appreciation raffles, Amplify awards prizes of substantial value. In strict accordance with United States federal tax laws, any participant who wins a prize of eligible value is required to be issued an IRS Form 1099-MISC.</p>
    <p className="mb-6">Winners will be required to provide tax documentation (W-9) and ID verification. If a winner does not complete verification within the stated period, the prize may be forfeited and an alternate winner selected. Required prize reporting information (name, address, taxpayer ID, prize value) will be shared with tax authorities and our payment processor. Please note that under the One Big Beautiful Bill Act, the federal Form 1099-MISC reporting threshold for prizes awarded after December 31, 2025, has increased to $2,000.</p>
    <p className="mb-6">Under the California Privacy Rights Act (CPRA) and allied state laws, an SSN constitutes Sensitive Personal Information (SPI). Amplify collects and processes this SPI exclusively for the business purpose of satisfying federal and state tax reporting obligations and verifying the identity of prize winners to prevent financial fraud. We do not use, sell, or share Sensitive Personal Information for any secondary purposes, including marketing or behavioral profiling. You have the right to limit the use of your sensitive data beyond what is necessary for these legally mandated business operations. To exercise this right, please utilize the "Limit the Use of My Sensitive Personal Information" link located in the footer of our website.</p>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">How We Share Your Information with Third Parties</h3>
    <p className="mb-6">Amplify operates as an intermediary to facilitate your charitable impact and administer appreciation sweepstakes. We do not sell, rent, or lease your personal data to third-party data brokers. We share your information strictly in the following operational contexts:</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>Recipient Charities and DAF Administrators:</strong> Donations processed for the purpose of this sweepstakes are remitted to a donor-advised fund administered by Our Change Foundation. By donating, you consent that Amplify may share your name, email, and donation amount with Change for receipting and grant administration. Change may contact you directly regarding your donation and to provide tax documentation where applicable. Unless you explicitly choose to make your donation anonymous or opt-out of information sharing during the checkout process, we will also share your name and email address with the recipient charity.</li>
      <li className="pl-2"><strong>Payment Processors:</strong> To ensure the highest level of financial security, Amplify does not natively store your credit card or bank account information. Payment card data is processed by Stripe — Amplify does not store full card numbers. We use encryption in transit and at rest and restrict access to a need-to-know basis.</li>
      <li className="pl-2"><strong>Infrastructure and Communication Providers:</strong> We share necessary data elements with strictly vetted third-party service providers, including Stripe, Google Analytics, SendGrid, AWS (hosting), and Change. Data may transfer to the U.S. and other countries; we use standard contractual clauses where required.</li>
      <li className="pl-2"><strong>Legal and Safety Obligations:</strong> We may disclose personal information to external entities, including law enforcement or state and federal tax authorities, when such disclosure is legally necessary to comply with subpoenas, investigate potential violations of civil or criminal law, or protect the integrity of our platform against fraud.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Sweepstakes Transparency and Publicity Rights</h3>
    <p className="mb-6">By participating in the monthly appreciation raffles administered by Amplify, you acknowledge that specific data processing practices are governed by state and federal sweepstakes laws, which may supersede certain general privacy rights regarding data deletion.</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>AMOE Scans and Retention:</strong> Alternate Method of Entry (AMOE) submissions (handwritten postcards and envelope postmarks) are scanned and retained for audit purposes for up to 3 years. Scanned images are stored encrypted; physical envelopes are stored in locked facilities accessible only to authorized staff. AMOE data will be used for eligibility verification, fraud detection, and public audit upon request.</li>
      <li className="pl-2"><strong>Winners List Mandate:</strong> To demonstrate the fairness and legality of our promotions, state laws require Amplify to maintain a ledger of major prize winners. We will share winner name and city publicly and will share required personal data with tax authorities and our payment processor to comply with reporting obligations. While you hold the right to request the deletion of your personal data under the CPRA, Amplify is legally obligated to retain and disclose this specific Winner List information to comply with state regulatory audits and legal obligations.</li>
      <li className="pl-2"><strong>Publicity Release:</strong> Putting a name and face to our winning entrants helps build trust in our community. If you are selected as a winner, we may request that you execute a separate Declaration of Compliance and Publicity Release. By signing this release, you grant Amplify permission to use your name, likeness, and details of your win for advertising and promotional purposes without further compensation, unless prohibited by law.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Your State Privacy Rights and How to Exercise Them</h3>
    <p className="mb-6">Depending on your state of residence, including under the California Privacy Rights Act (CPRA), you are granted specific legal rights regarding your personal data. Amplify respects these rights and provides mechanisms for all U.S. and EEA users to exercise them equally:</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>The Right to Know and Access:</strong> You have the right to request that we disclose the specific pieces of personal information we have collected about you, the sources of that information, our business purposes for collecting it, and the categories of third parties with whom it is shared.</li>
      <li className="pl-2"><strong>Data Retention & Deletion Process:</strong> General account data is retained for 7 years. AMOE scans & audit data are retained for 3 years. Payment receipts are retained for 7 years. To request deletion, email privacy@amplify.org with the subject "Data Deletion Request." Please note that we may deny your deletion request if retaining the information is legally necessary for us to fulfill the terms of a charitable pledge, comply with IRS tax reporting, or comply with state laws mandating the retention of sweepstakes records.</li>
      <li className="pl-2"><strong>Cookies & Tracking (Opt-Outs):</strong> You have the right to direct us not to sell or share your personal information. Users may manage their cookie settings and disable tracking for ad targeting and remarketing via the "Cookie Preferences" link in our footer.</li>
      <li className="pl-2"><strong>Opt-in Marketing Consents & Unsubscribe:</strong> Users may opt-out of marketing emails at any time via the unsubscribe link or by emailing privacy@amplify.org.</li>
      <li className="pl-2"><strong>The Right to Correction & Non-Discrimination:</strong> You have the right to correct inaccurate personal data. Amplify will never deny you services or charge you different prices because you exercised your privacy rights.</li>
      <li className="pl-2"><strong>Contact & Complaint Route:</strong> For verifiable consumer requests, or to escalate complaints, please email our privacy officer at privacy@amplify.org. If unsolved, you may escalate to legal@amplify.org. We also automatically detect and honor opt-out preference signals, including the Global Privacy Control (GPC), broadcasted by your browser.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Charitable Disclosures and State Reporting</h3>
    <p className="mb-6">Amplify operates transparently as an intermediary platform facilitating charitable pledges. In compliance with the fundraising laws of various states, we provide specific disclosures to educate prospective donors about the financial mechanics of our platform. When you make a pledge through Amplify, the exact financial breakdown of your contribution—including the percentage routed to the recipient charity, the percentage allocated to the appreciation raffle prize pool, and the platform administrative fee—is explicitly detailed at the point of checkout. We are registered as required under applicable state charitable solicitation acts. For a comprehensive list of state-specific disclosure statements, please review our Charitable Solicitation Disclosure Addendum, accessible via the footer of our website.</p>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Data Security and Breach Notification</h3>
    <p className="mb-6">Amplify takes the security of your personal, financial, and tax information with the utmost seriousness. Payment card data is processed by Stripe — Amplify does not store full card numbers. We use encryption in transit and at rest and restrict access to a need-to-know basis.</p>
    <p className="mb-6">While we employ rigorous security measures, no digital platform is entirely invulnerable. In the event of a security incident that compromises your unencrypted personal information, Amplify maintains a comprehensive breach response protocol. We will notify affected users without undue delay and in accordance with applicable law, and we will act rapidly to secure our systems and investigate the scope of the incident.</p>

    <h3 className="text-lg md:text-xl font-black uppercase text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">Children's Privacy</h3>
    <p className="mb-6">The services provided by Amplify, including our charitable pledge systems and monthly appreciation raffles, are strictly not intended for under-18s. If you are under 18 do not register. We do not knowingly solicit, collect, or maintain personal information from children under the age of 13, in strict compliance with the Children's Online Privacy Protection Act (COPPA), nor do we permit minors to utilize our platform. If you are a parent or guardian and discover that your child has provided us with personal information without your consent, please contact us immediately at privacy@amplify.org. Upon verification, we will take immediate steps to systematically delete any information that we learn is from a child under 13 from our databases and terminate the associated account.</p>
  </>
);

export default PrivacyPolicyContent;
