import React from 'react';

const RulesContent = () => (
  <>
    <p className="text-xs md:text-sm font-bold text-slate-500 mb-2">
      Amplify Giving Circles — Master Official Rules. Master Rules Version 1.0, dated [INSERT VERSION DATE].
    </p>
    <p className="uppercase font-bold text-xs md:text-sm tracking-wider text-slate-500 mb-10 md:mb-14">
      No purchase, payment, or donation is necessary to enter or win. A purchase, payment, or donation will not improve your chances of winning. Void where prohibited.
    </p>

    <p className="mb-6">These Master Official Rules do not by themselves govern any Drawing. Each Drawing is governed by a Supplemental Drawing Addendum that incorporates a specific version of these Master Official Rules. The registration and bonding status applicable to any particular Drawing is stated in that Drawing's Addendum.</p>
    <p className="mb-6">Contributions are collected by the Sponsor and transferred to [DAF SPONSOR LEGAL NAME], a Section 501(c)(3) sponsoring organization that maintains charitable funds (EIN [INSERT EIN]) (the "Foundation").</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">1 &nbsp;&nbsp; Sponsor and Promotion Structure</h3>
    <p className="mb-6">The Sponsor is Amplify Give LLC, 7901 4th St N, Ste 32498, St. Petersburg, FL 33702, a Florida limited liability company (the "Sponsor" or "Amplify").</p>
    <p className="mb-6">The promotion consists of concurrent sweepstakes organized by membership Tier: Silver, Gold, and Diamond (each, a "Tier"). Within each Tier, paid Participants are grouped into "Circles" of up to 400 paid Participants each. Each Circle has its own separate entry pool. Entries are never shared between Circles, and no entry is eligible for more than one Circle's Drawing.</p>
    <p className="mb-6">Each specific Drawing, including each Circle's guaranteed first Drawing and each Tier's recurring monthly Drawings, has its own Drawing Addendum stating the entry period, the Circle or Circles and Tier or Tiers covered, the applicable Drawing Date, and the prize schedule and total approximate retail value for that Drawing, as described in Section 9. Where required for state registration, each Addendum is filed as its own discrete promotion, either per Circle, per Tier, or, where permitted, combined across Tiers.</p>
    <p className="mb-6">There are two types of Drawing Addendum. A "Circle Launch Addendum" is filed before a Circle opens for enrollment and covers only that Circle's guaranteed first Drawing. A "Monthly Drawing Addendum" is filed for each monthly Drawing period and covers the recurring monthly Drawings of Active Circles for that period.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">2 &nbsp;&nbsp; Promotion Period</h3>
    <p className="mb-6">The entry period, opening date, Drawing Date, and, for a Circle Launch Addendum, the Backstop End Date applicable to any given Drawing are stated in that Drawing's Addendum, which is posted on the Platform at https://amplifygive.com/official-rules. All times are Eastern Time, and the Sponsor's computer is the official timekeeper.</p>
    <p className="mb-6">Each Circle's first Drawing is guaranteed to occur on or before the Backstop End Date stated in that Circle's Launch Addendum, as described in Section 8.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">3 &nbsp;&nbsp; Definitions</h3>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>"Active Circle"</strong> means a Circle that has held its first Drawing and is participating in recurring monthly Drawings.</li>
      <li className="pl-2"><strong>"AMOE"</strong> means the free alternative method of entry described in Section 7.</li>
      <li className="pl-2"><strong>"Backstop End Date"</strong> means the date stated in a Circle's Launch Addendum by which that Circle's guaranteed first Drawing will be held if the Circle has not yet reached 400 paid Participants. The Backstop End Date is always set as a fixed monthly Drawing Date.</li>
      <li className="pl-2"><strong>"Circle"</strong> means a group of up to 400 paid Participants in a single Tier.</li>
      <li className="pl-2"><strong>"Contribution"</strong> means a monthly payment a Participant authorizes through the Platform, which the Sponsor collects and transfers to the Foundation.</li>
      <li className="pl-2"><strong>"Currently-Open Pool"</strong> means any Circle, whether Filling or Active, that is currently accepting entries for an open Drawing period, used to determine AMOE allocation under Section 7.</li>
      <li className="pl-2"><strong>"Drawing"</strong> means the random selection of winners for a Circle for a given period.</li>
      <li className="pl-2"><strong>"Drawing Addendum"</strong> means a supplemental document, incorporating a specific version of these Official Rules by reference, that states the entry period, the Circle or Circles and Tier or Tiers covered, the prize schedule, and the Drawing Date for a specific Drawing, and that is filed as its own promotion where required by state law.</li>
      <li className="pl-2"><strong>"Drawing Date"</strong> means the fixed monthly date on which Drawings occur, which is the [5th] day of each calendar month, or the next business day if that day is not a business day, unless a different date is stated in an applicable Drawing Addendum.</li>
      <li className="pl-2"><strong>"Filling Circle"</strong> means a Circle that has not yet held its first Drawing.</li>
      <li className="pl-2"><strong>"Master Rules Version"</strong> means the dated version of these Official Rules in effect and incorporated by reference at the time a given Drawing Addendum commences.</li>
      <li className="pl-2"><strong>"Participant"</strong> means a person who has joined a Circle.</li>
      <li className="pl-2"><strong>"Retired Circle"</strong> means a Filling Circle that reached its Backstop End Date without reaching 400 paid Participants, held its guaranteed first Drawing on that basis, and does not become an Active Circle.</li>
      <li className="pl-2"><strong>"Platform"</strong> means the Amplify website and application at amplifygive.com.</li>
      <li className="pl-2"><strong>"Supported Organization"</strong> means a charitable organization appearing on the list of vetted charitable organizations made available on the Platform.</li>
      <li className="pl-2"><strong>"Tier"</strong> means the Silver, Gold, or Diamond membership level.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">4 &nbsp;&nbsp; Eligibility</h3>
    <p className="mb-6">The promotion is open only to natural persons who are legal residents of one of the fifty (50) United States or the District of Columbia and who are at least eighteen (18) years old (at least nineteen (19) in Alabama and Nebraska, and at least twenty-one (21) in Mississippi) and who have reached the age of majority in their state of residence at the time of entry. Employees, contractors, officers, managers, and members of the Sponsor, and their respective affiliates and advertising and promotion agencies, and the immediate family members of each of the foregoing, are not eligible. "Immediate family members" means spouse, parents, siblings, children, and any person living in the same household. All entrants are subject to sanctions screening and identity verification. Void where prohibited.</p>
    <p className="mb-6">Entries must be submitted by the authorized account holder. The Sponsor may disqualify any entrant who tampers with the promotion, uses automated means to enter, violates these Official Rules, or submits false information.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">5 &nbsp;&nbsp; How Circles Work; Charging; Assignment</h3>
    <p className="mb-6">A person joins a Tier through the Platform and is assigned by the Sponsor to a Circle within that Tier. Circle assignment is administrative and is not selected by the Participant. The first Contribution is charged immediately upon joining. For a Filling Circle, recurring monthly Contributions begin only once the Circle reaches 400 paid Participants. Each Circle may contain no more than 400 paid Participants.</p>
    <p className="mb-6">If the number of paid Participants in a Tier declines, the Sponsor may consolidate Circles within that Tier by reassigning Participants among Circles of the same Tier, provided that no Circle shall exceed the cap of 400 paid Participants. Consolidation does not change a Participant's Tier, Contribution amount, prize schedule, or the number of entries a Participant receives. Reassignment following a Retired Circle's guaranteed first Drawing is described in Section 8.</p>
    <p className="mb-6">Reassignment among Circles of the same Tier and the allocation of free AMOE entries under Section 7 both use the same neutral, non-discretionary administrative process, so that no Participant, paid or free, is advantaged or disadvantaged relative to any other by the assignment method itself.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">6 &nbsp;&nbsp; Contributions, Entries, and the No-Rollover Rule</h3>
    <p className="mb-6">Each Contribution creates exactly one entry into the next Drawing held for the Participant's Circle. For a Filling Circle, that is the Circle's guaranteed first Drawing. For an Active Circle, that is the next recurring monthly Drawing. A Contribution's entry remains valid and is not forfeited or expired by the passage of time between the Contribution and that Drawing.</p>
    <p className="mb-6">Entries never roll over between Drawings. Once a Drawing is held, all entries in that Drawing, winning and non-winning alike, are discarded and are not eligible for any later Drawing. No Participant accumulates entries across Drawing periods.</p>
    <p className="mb-6">Cancellation stops all future Contributions and all future entries. If a Participant has already been charged, that Contribution's entry remains valid for the next Drawing held for that Participant's Circle. A Participant is not entered in any Drawing for a period in which the Participant has not been charged.</p>
    <p className="mb-6">Contributions are irrevocable completed charitable gifts to the Foundation upon transfer to the Foundation and are final and non-refundable. See Section 14.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">7 &nbsp;&nbsp; Free Alternative Method of Entry (AMOE)</h3>
    <p className="mb-6">To enter a Drawing without a Contribution, an entrant must hand print their full name, street address, city, state, ZIP code, date of birth, the Tier they wish to enter, and the applicable Drawing Date on a plain postcard and mail it to: Amplify Give LLC AMOE, 7901 4th St N, Ste 32498, St. Petersburg, FL 33702.</p>
    <p className="mb-6">Limit one (1) entry per person per Tier per Drawing period, regardless of method of entry (Contribution or AMOE); a person who has a paid entry for a Tier's Drawing may not also submit an AMOE entry for that same Tier's Drawing. There is no limit on the total number of AMOE entries received across all entrants. A postcard is valid only for a single Drawing period that is open at the time the postcard is postmarked, and only for the period specified on the postcard, or, if no period is specified, for the current open Drawing period in which it is received. Entries submitted in advance for future Drawing periods are void. To enter multiple periods, mail a separate postcard for each period.</p>
    <p className="mb-6"><strong>Allocation of AMOE entries among Circles.</strong> A Tier may have more than one Currently-Open Pool at a given time, consisting of Active Circles accepting entries for the current period together with any Filling Circle or Circles. Each valid AMOE entry received for a Tier is assigned to one Currently-Open Pool in that Tier by a neutral round-robin rotation that cycles through all Currently-Open Pools in that Tier in ascending Circle number order, restarting at the beginning of each Drawing period. The rotation is applied in the order entries are received and involves no discretion on the part of the Sponsor. An AMOE entrant may not choose which Circle receives the entry, in the same way that a paid Participant may not choose which Circle receives their Contribution.</p>
    <p className="mb-6">AMOE entries do not count toward the 400 paid-Participant capacity of any Circle or toward the trigger in Section 8. Once assigned to a Circle, an AMOE entry is combined into a single pool with the paid entries for that Circle and Drawing period, carries identical odds within that pool, is eligible for every prize offered in that Drawing on identical terms, and is treated with equal dignity in all respects.</p>
    <p className="mb-6">All AMOE postcards for a given Drawing must be postmarked no later than seven (7) days before the applicable Drawing Date and received no later than two (2) business days before the applicable Drawing Date.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">8 &nbsp;&nbsp; Guaranteed First Drawing; Transition to Recurring Drawings</h3>
    <p className="mb-6">Each Circle's first Drawing is guaranteed to occur. The first Drawing occurs on the earlier of: (a) the first fixed monthly Drawing Date that is at least fourteen (14) days after the Circle reaches 400 paid Participants; or (b) the Backstop End Date. The Sponsor has no discretion to cancel, postpone, or roll Participants forward.</p>
    <p className="mb-6">The full prize schedule stated in a Circle's Launch Addendum is awarded at that Circle's first Drawing regardless of the number of paid Participants enrolled at that time.</p>
    <p className="mb-6">If a Filling Circle reaches 400 paid Participants, after its first Drawing it becomes an Active Circle and continues with recurring monthly Drawings on each fixed monthly Drawing Date, each governed by a separately filed Monthly Drawing Addendum incorporating the Master Rules Version in effect when that Addendum commences. If a Filling Circle instead reaches its Backstop End Date without reaching 400 paid Participants, its first Drawing will still be held as guaranteed, as described above. Following that Drawing, the Circle becomes a Retired Circle: it does not become an Active Circle, no further Contributions are charged to its Participants, and it will not hold any further Drawings.</p>
    <p className="mb-6">Each Participant of a Retired Circle is reassigned by the Sponsor to an Active Circle in the same Tier that has fewer than 400 paid Participants, using the same neutral, non-discretionary process described in Section 5. The Participant's Tier, Contribution amount, and prize schedule are unchanged, and recurring monthly Contributions begin upon reassignment. If no Active Circle in that Tier has room at the time of retirement, the Participant is not charged until an Active Circle in that Tier has room. The Sponsor will notify the Participant when their Circle retires, and will provide advance notice before reassignment stating the date the first recurring Contribution will be charged and the amount.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">9 &nbsp;&nbsp; Prizes and Approximate Retail Values</h3>
    <p className="mb-6">The complete prize schedule for a specific Drawing, including every prize tier, prize amount, and number of winners, and the total approximate retail value (ARV) for that Drawing, is stated in that Drawing's Addendum. All prizes are awarded as cash, and ARV equals the stated cash amount. Where an Addendum covers more than one Circle or Tier, the Addendum states the total ARV across all Circles and Tiers covered by that Addendum.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">10 &nbsp;&nbsp; Odds</h3>
    <p className="mb-6">Odds of winning depend on the total number of eligible entries received for the applicable Circle and Drawing period. Because each Circle is capped at 400 paid Participants, and because AMOE entries are received in an unlimited quantity and allocated across Currently-Open Pools as described in Section 7, the total number of entries in any given Circle's Drawing may exceed 400. Paid entries and AMOE entries within the same Circle and Drawing period carry identical odds.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">11 &nbsp;&nbsp; Winner Selection</h3>
    <p className="mb-6">For each Drawing, winners are selected using a documented random-selection procedure with a tested random number generator and an auditable record of the frozen eligible-entry population and the selection results, or by a certified third party. For each Circle, a number of unique winners equal to the number of prizes for that Tier is selected to form the winners pool. If the number of prizes for a Circle exceeds the number of unique eligible entrants for that Circle, each eligible entrant receives one prize before any entrant receives a second; any remaining prizes are then assigned by additional random drawings in which entrants who already won may again participate. Prizes are then randomly assigned within the winners pool without replacement.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">12 &nbsp;&nbsp; Winner Notification, Documentation, and Finality</h3>
    <p className="mb-6">The promotion is self-administered by the Sponsor; no third-party administrator is used. Potential winners will be notified within forty-eight (48) hours of the Drawing using the contact information on file. A potential winner may be required to sign and return an Affidavit of Eligibility, a Liability Release, and, where permitted by law, a Publicity Release, and to provide a valid government-issued photo ID and a completed IRS Form W-9; all required documents must be completed, signed, and returned within ten (10) days after the date they are sent to the potential winner. Where the prize awarded is valued at ten thousand dollars ($10,000) or more, the Sponsor requires that the Affidavit of Eligibility be notarized as a condition of payment. The Sponsor will issue an IRS Form 1099-MISC where required by law. All taxes on prizes are the sole responsibility of the winner. If a potential winner is ineligible, cannot be verified, does not respond in time, or declines the prize, the Sponsor will randomly select a successive alternate from the remaining eligible entries in the same pool, continuing until the prize is awarded. All winner determinations are final.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">13 &nbsp;&nbsp; Prize Fulfillment</h3>
    <p className="mb-6">Prizes are paid by the Sponsor from the Sponsor's own funds and are reimbursed to the Sponsor by the Foundation as a documented fundraising expense, separate from and in addition to the Sponsor's platform fee described in Section 14. Prizes are never a pass-through of Participant Contributions. Prizes will be fulfilled within thirty (30) business days after the winner returns all required documentation, by the payment method the Sponsor selects, which may include check, ACH transfer, or wire transfer. Where an electronic payment method is used, the winner will be asked to provide banking information through a secure channel separate from the Affidavit of Eligibility. Prizes are non-transferable.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">14 &nbsp;&nbsp; Contributions and Use of Proceeds</h3>
    <p className="mb-6">The Sponsor is the merchant of record for Contribution charges and, together with its payment processor, is responsible for processing the charge and any related billing dispute. The Sponsor uses Stripe Connect to transfer each Contribution to the Foundation, which receives the funds, has exclusive legal control over them, and issues the Contribution receipt. A Contribution becomes an irrevocable completed charitable gift to the Foundation once it is transferred to and received by the Foundation, and is not refundable. Billing reversals, chargebacks, and corrections after transfer are handled as described in Section 13 of the Terms of Use.</p>
    <p className="mb-6">The Sponsor's platform fee is compensation the Foundation pays the Sponsor for the fundraising, technology, and administrative services the Sponsor provides to the Foundation. The platform fee, together with third-party payment processing fees, the Foundation's administration fee, and reimbursement of prize costs, is deducted from Contributions before the net amount is granted to Supported Organizations.</p>
    <p className="mb-6">Participants may vote for how their Tier's pooled Contributions are recommended for grant among the Supported Organizations made available on the Platform, as described in Section 15 and the Terms of Use.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">15 &nbsp;&nbsp; Voting Does Not Affect the Sweepstakes</h3>
    <p className="mb-6">Casting a vote for a Supported Organization has no effect on any Drawing. It does not affect the number of entries a Participant receives, the odds of winning, eligibility for any prize, the prizes offered, or the conduct of any Drawing. Participants who make no selection, and entrants who enter by AMOE and make no Contribution, receive entries on identical terms and with identical odds.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">16 &nbsp;&nbsp; Taxes and Charitable Deductibility</h3>
    <p className="mb-6">The federal and state tax treatment of a Contribution, and the deductible amount if any, are determined under applicable tax law and will be reflected in the Foundation's contribution acknowledgment. Amplify does not determine deductibility. Entrants who enter by AMOE make no payment and therefore make no charitable contribution. No purchase, payment, or contribution is necessary to enter or win.</p>
    <p className="mb-6">Prize winnings are taxable income to the winner. All federal, state, and local taxes on prizes are the sole responsibility of the winner. Neither the Sponsor nor the Foundation provides tax advice; winners and Participants should consult their own tax advisors. See the Terms of Use for the complete tax treatment of a Contribution.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">17 &nbsp;&nbsp; Recurring Billing and Cancellation</h3>
    <p className="mb-6">By joining a Tier, a Participant authorizes the Sponsor to charge the Participant's first Contribution on joining and, once the Participant's Circle reaches 400 paid Participants, recurring monthly Contributions in the amount stated for that Tier until the Participant cancels. Each Contribution is transferred to the Foundation as described in Section 14, and each monthly charge creates one new entry as described in Section 6. A Participant may cancel at any time through the self-service cancellation tools in the account section of the Platform; cancellation is effective immediately as to all future charges and future entries but, as described in Section 6, does not remove the Participant from any Drawing for which the Participant has already been charged. Full billing disclosures, the Participant's consent to recurring charges, and cancellation mechanics are described in the Terms of Use and disclosed to the Participant before enrollment.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">18 &nbsp;&nbsp; Not Sponsored by Social Platforms</h3>
    <p className="mb-6">This promotion is not sponsored, endorsed, administered by, or associated with any social media platform.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">19 &nbsp;&nbsp; General Release</h3>
    <p className="mb-6">By entering, each entrant releases and holds harmless the Sponsor, the Foundation, the Supported Organizations listed on the Platform, any social media or other third-party platform used to promote this promotion, and each of their respective affiliates, officers, managers, members, employees, contractors, and agents from any and all liability, claims, or damages arising out of participation in this promotion or the acceptance, use, or misuse of any prize, including without limitation claims for personal injury, property damage, or violation of publicity or privacy rights.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">20 &nbsp;&nbsp; Limitation of Liability</h3>
    <p className="mb-6">The released parties are not responsible for lost, late, misdirected, or illegible entries, technical failures, or errors in administration. Entries are logged in Eastern Time using the Sponsor's computer as the official timekeeper.</p>
    <p className="mb-6">To the fullest extent permitted by law, the released parties are not liable for indirect, incidental, consequential, special, or punitive damages arising out of participation in this promotion or the acceptance, use, or misuse of any prize, and the released parties' total aggregate liability to any entrant is limited to the cost of the entrant's Contribution, if any, giving rise to the claim.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">21 &nbsp;&nbsp; No Cancellation of a Commenced Drawing</h3>
    <p className="mb-6">The Sponsor may not cancel, postpone, or fail to hold any Drawing governed by a Drawing Addendum that has commenced. If fraud, technical failure, or other cause beyond the Sponsor's control corrupts the administration, security, or integrity of a Drawing, the Sponsor may take corrective action, but each affected Drawing will still be held and winners will be selected at random from the eligible entries received for the applicable pool.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">22 &nbsp;&nbsp; Force Majeure</h3>
    <p className="mb-6">The Sponsor is not liable for any failure or delay caused by events beyond its reasonable control, except that the guaranteed Drawing obligation in Section 8 and the no-cancellation obligation in Section 21 remain in effect, and except to the minimum extent required by a final court order, regulator directive, or applicable law, in which case the Sponsor will use the nearest lawful method or date that preserves all eligible entries and advertised prizes.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">23 &nbsp;&nbsp; Versioning, Modification, and Discontinuation</h3>
    <p className="mb-6">These Master Rules are versioned, and each Drawing Addendum states the Master Rules Version it incorporates. The Sponsor may revise these Master Rules prospectively, but a revised version applies only to Drawing Addenda that commence after the revision takes effect. Once a Drawing Addendum has commenced, that Addendum and the Master Rules Version it incorporates are fixed for that Drawing, will not be changed, modified, or altered by any later revision, and the Drawing will be held and paid out in accordance with them. Each version is dated and archived on the Platform, and the version applicable to any Drawing is identified in that Drawing's Addendum.</p>
    <p className="mb-6">The Sponsor may discontinue the program, in whole or as to any Tier, by ceasing to file new Drawing Addenda. Every Drawing Addendum that has already commenced will run to completion and all prizes stated in it will be awarded. In the event of discontinuation, the Sponsor will provide notice on the Platform and by email to affected Participants, and no further Contributions will be charged after the last commenced Drawing period concludes.</p>
    <p className="mb-6">If a Participant does not wish to continue participating under a revised Master Rules Version, the Participant may cancel at any time as described in Section 17.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">24 &nbsp;&nbsp; Winners List and Rules Access</h3>
    <p className="mb-6">For a copy of these Master Official Rules, any Drawing Addendum, or a list of winners, visit https://amplifygive.com/official-rules or write to Amplify Give LLC, 7901 4th St N, Ste 32498, St. Petersburg, FL 33702. The winners list is provided free of charge. Residents of Vermont may omit return postage.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">25 &nbsp;&nbsp; Privacy; Data Storage; Opt-Out</h3>
    <p className="mb-6">Information submitted is handled per the Sponsor's Privacy Policy at https://amplifygive.com/privacy. Data is stored in the United States. Entrants may opt out of promotional communications as described in the Privacy Policy.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">26 &nbsp;&nbsp; Disputes</h3>
    <p className="mb-6 uppercase font-bold text-sm tracking-wide text-slate-700">
      Governing law and dispute resolution. These Official Rules are governed by Florida law. Any dispute will be resolved by binding individual arbitration administered by the American Arbitration Association under its Consumer Arbitration Rules, on the terms stated in the version of the Platform Terms of Use in effect on the date the applicable Drawing Addendum commences, which version is archived on the Platform and includes a 30-day opt-out running from the date of entry, an informal resolution requirement, mass arbitration procedures, and a small claims exception. A later amendment to the Terms of Use does not affect the arbitration terms applicable to a Drawing that has already commenced. Entrants waive any right to a jury trial and any right to participate in a class action. Venue for any permitted court proceeding is Pinellas County, Florida. Each entrant waives California Civil Code Section 1542, which reads: "A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party."
    </p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">27 &nbsp;&nbsp; Referenced Documents; Severability; Headings</h3>
    <p className="mb-6">The Terms of Use and Privacy Policy are referenced for platform-use and data-processing matters but are not incorporated into these Master Official Rules as rules governing a Drawing. No later amendment to the Terms of Use or Privacy Policy modifies a commenced Drawing. If an applicable Drawing Addendum expressly incorporates any provision of another agreement, that Addendum will identify the version and effective date incorporated, and that version will remain fixed for the Drawing. Each Drawing Addendum incorporates a specific version of these Master Official Rules. If any provision is held invalid, the remaining provisions remain in effect. Headings are for convenience only.</p>
  </>
);

export default RulesContent;
