import React from 'react';

const TermsContent = () => (
  <>
    <p className="text-xs md:text-sm font-bold text-slate-500 mb-10 md:mb-14">
      Version 1.0 · Effective Date: [INSERT EFFECTIVE DATE].
    </p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">1 &nbsp;&nbsp; Introduction and Acceptance</h3>
    <p className="mb-6">These Terms of Use ("Terms") form a binding agreement between you and Amplify Give LLC ("Amplify," "we," "us," or "our"), a Florida limited liability company, and govern your access to and use of our websites, mobile experiences, applications, and related services (collectively, the "Services"). By creating an account, making a contribution, entering a prize drawing, or otherwise accessing or using the Services, you acknowledge that you have read, understood, and agree to be bound by these Terms and by our Privacy Policy, which is incorporated into these Terms by reference. If you do not agree, you must not use the Services.</p>
    <p className="mb-6 uppercase font-bold text-sm tracking-wide text-slate-700">
      Please read Section 26 (Governing Law and Dispute Resolution) carefully. It requires most disputes to be resolved by binding individual arbitration seated in Florida and contains a class action waiver. You may opt out of arbitration as described in that section.
    </p>
    <p className="mb-6">If you are entering into these Terms on behalf of a company or other legal entity, you represent that you have authority to bind that entity.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">2 &nbsp;&nbsp; Our Services</h3>
    <p className="mb-6">Amplify operates a for-profit promotional platform that facilitates charitable giving. Users make voluntary recurring monthly contributions and, as a thank-you, receive entries into promotional prize drawings. Amplify is a for-profit business. Amplify is not a charity, is not a tax-exempt organization, and does not itself maintain charitable funds. Amplify acts as a professional fundraiser (in some states referred to as a paid solicitor) providing fundraising, technology, and administrative services to the Foundation under a written services agreement, for which Amplify is compensated by the Foundation as described in Section 11. Amplify does not provide tax, legal, accounting, or financial advice, and nothing in the Services should be relied upon as such advice.</p>
    <p className="mb-6">Amplify maintains the registrations, filings, and bonds required for its activities where applicable. Required state charitable solicitation disclosures are available at amplifygive.com/disclosures and are addressed on donation pages where a specific state requires point-of-solicitation display.</p>
    <p className="mb-6"><strong>Relationship to the Foundation.</strong> Amplify's relationship to the Foundation is that of an independent contractor. Amplify acts as the Foundation's limited agent solely for the specific administrative functions described in these Terms, including tallying member votes and submitting monthly allocation recommendations as described in Section 10. Nothing in these Terms creates a partnership, joint venture, general agency, or fiduciary relationship between Amplify and the Foundation, and Amplify is not authorized to bind the Foundation beyond that limited purpose.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">3 &nbsp;&nbsp; Definitions</h3>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>"AMOE"</strong> means the free Alternative Method of Entry described in Section 9 and detailed in the Official Rules.</li>
      <li className="pl-2"><strong>"Supported Organization"</strong> means a charitable organization appearing on the Supported Organization List for which you may cast your vote, as described in Section 8.</li>
      <li className="pl-2"><strong>"Supported Organization List"</strong> means the list of charitable organizations made available on the Services from which you may select Supported Organizations. Amplify may add or remove organizations from the Supported Organization List at any time.</li>
      <li className="pl-2"><strong>"Drawing Addendum"</strong> means a supplemental document that governs a specific Prize Drawing, states the entry period, the Circles or Tiers covered, the prize schedule, and the drawing date for that Prize Drawing, and incorporates by reference a specific dated version of the Master Rules.</li>
      <li className="pl-2"><strong>"Master Rules"</strong> means the Amplify Giving Circles Master Official Rules, the evergreen document incorporated by reference into each Drawing Addendum.</li>
      <li className="pl-2"><strong>"Circle"</strong> means a capped giving group that Amplify offers at a defined monthly contribution tier.</li>
      <li className="pl-2"><strong>"Contribution"</strong> means a voluntary monthly payment you authorize through the Services.</li>
      <li className="pl-2"><strong>"Foundation"</strong> means the independent Internal Revenue Code Section 501(c)(3) sponsoring organization that maintains charitable funds to which Contributions are remitted.</li>
      <li className="pl-2"><strong>"Official Rules"</strong> means, together, the Master Rules and the applicable Drawing Addendum that govern a specific Prize Drawing.</li>
      <li className="pl-2"><strong>"Prize Drawing" or "drawing"</strong> means a promotional sweepstakes conducted through the Services in which winners are selected by chance.</li>
      <li className="pl-2"><strong>"Sponsor"</strong> means the entity identified as the sponsor of a given drawing in the applicable Official Rules.</li>
      <li className="pl-2"><strong>"Tier"</strong> means a contribution level at which Circles are offered.</li>
    </ul>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">4 &nbsp;&nbsp; Eligibility</h3>
    <p className="mb-6">The Services and the Prize Drawings are open only to natural persons who are at least eighteen (18) years old (or the age of legal majority in their state of residence, whichever is greater) and who are legal residents of the fifty (50) United States and the District of Columbia. The Services and the Prize Drawings are void where prohibited or restricted by law.</p>
    <p className="mb-6">Eligibility for any specific drawing is governed by the applicable Official Rules, which control over these Terms on questions of eligibility for that drawing. Amplify may restrict availability of the Services in any jurisdiction as required by law, but the Prize Drawings are offered nationwide except where prohibited. Employees, contractors, officers, managers, and members of Amplify, and their respective affiliates, agents, and immediate family and household members, may be excluded from participation to the extent set out in the applicable Official Rules. You are responsible for compliance with all laws applicable to you.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">5 &nbsp;&nbsp; Accounts and Security</h3>
    <p className="mb-6">You must register for an account to make Contributions. You agree to provide accurate, current, and complete information and to keep it current. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account, whether or not authorized by you. You agree to notify us immediately of any unauthorized access or use. We may refuse registration, or suspend or terminate an account, in our discretion, including where we suspect fraud or a violation of these Terms or the Official Rules. You may not share, sell, or transfer your account.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">6 &nbsp;&nbsp; Privacy</h3>
    <p className="mb-6">Your use of the Services is subject to our Privacy Policy, which describes how we collect, use, disclose, and protect your information and your choices, including how your Contribution and Circle participation data may be shared with the Foundation. By using the Services, you consent to the data practices described in the Privacy Policy.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">7 &nbsp;&nbsp; Circles and Tiers</h3>
    <p className="mb-6">Amplify offers Circles at multiple contribution Tiers. Each Circle has a defined capacity, and enrollment in a Circle is capped. When you join a Circle, you authorize recurring monthly billing as described in Section 11. Your first Contribution is charged at signup. Recurring monthly charges begin once your Circle fills. The structure, capacity, and Tier of each Circle are described at the point of enrollment.</p>
    <p className="mb-6">If your Circle does not reach capacity by its Backstop End Date, it holds its guaranteed first Prize Drawing and then retires, as described in the Official Rules. If your Circle retires, Amplify will reassign you to an Active Circle in the same Tier with available capacity, and your recurring monthly Contributions begin upon reassignment; Amplify will notify you in advance of the date your first recurring Contribution will be charged and the amount. If no Active Circle in your Tier has capacity, you will not be charged until one does. Your Tier, Contribution amount, and prize schedule do not change.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">8 &nbsp;&nbsp; Voting for Supported Organizations</h3>
    <p className="mb-6">After completing enrollment, you will be invited to select up to four (4) organizations from the Supported Organization List; making a selection is optional. Each time you are charged a Contribution, you cast one vote toward your Tier's monthly allocation. If you select between one and four organizations, your single vote is divided equally among them (selecting four organizations does not give you four votes; it splits your one vote four ways). If you make no selection, your vote is divided equally among all of our Supported Organizations. Your vote is one input, among all votes cast that month by other members of your Tier, into the allocation Amplify recommends to the Foundation for your Tier, as described in Section 10; it is not itself a direction, earmark, or designation of your Contribution, and it is not a recommendation to the Foundation. Amplify does not track any Contribution to any individual charitable outcome.</p>
    <p className="mb-6">You may vote only for organizations appearing on the Supported Organization List; these organizations are vetted before being listed. You may request that an organization be added to the list through your account; Amplify will vet any requested organization, but listing it is not guaranteed. Amplify may add or remove organizations from the Supported Organization List at any time. If Amplify removes an organization you selected, your vote is divided among any of your remaining selections; if none of your selections remain, your vote is divided equally among all of our Supported Organizations. We will notify you if a selection of yours is removed.</p>
    <p className="mb-6">You may change your selection at any time through your account. A selection must be in place before your monthly Contribution is charged to apply to that Contribution; a change made after a charge applies starting with your next Contribution.</p>
    <p className="mb-6">Your vote for a Supported Organization has no effect on any Prize Drawing, including the number of entries you receive, your odds of winning, or your eligibility for any prize.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">9 &nbsp;&nbsp; Sweepstakes</h3>
    <p className="mb-6">No purchase and no Contribution is necessary to enter or win a Prize Drawing. A free Alternative Method of Entry (AMOE) is available, and entries submitted through the AMOE are treated equally with entries associated with Contributions, including with respect to odds of winning. Making a Contribution does not improve your chances of winning.</p>
    <p className="mb-6">Each Prize Drawing is governed by its own Drawing Addendum together with the dated version of the Master Rules that the Addendum incorporates by reference. Together these specify the entry period, prize description and approximate retail value, eligibility, entry methods (including the AMOE), odds, winner selection and notification, and any other material terms. Each Drawing Addendum, and every archived version of the Master Rules, is posted at the Official Rules page on the Services and remains available there after the drawing it governs has concluded. The Official Rules control over these Terms with respect to sweepstakes mechanics. In the event of any conflict between these Terms and the Official Rules on sweepstakes mechanics, the Official Rules govern. Every Circle's first Prize Drawing is guaranteed to occur no later than its Backstop End Date, and a Circle reaching capacity accelerates that first Prize Drawing to an earlier fixed monthly drawing date. Each Circle's recurring monthly Prize Drawings occur on the drawing date stated in the applicable Drawing Addendum. Once a Drawing Addendum has commenced, neither it nor the Master Rules version it incorporates will be changed, the Sponsor has no discretion to cancel, postpone, or fail to hold the Prize Drawing it governs, and the Prize Drawing will be held and paid out. A Circle's first Prize Drawing and its recurring monthly Prize Drawings are conducted under separately filed Drawing Addenda, each of which controls the drawing it governs.</p>
    <p className="mb-6">Amplify may revise the Master Rules and may discontinue the program, in whole or as to any Tier, as described in the Official Rules. If you do not wish to continue under a revised Master Rules Version, you may cancel at any time as described in Section 13.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">10 &nbsp;&nbsp; Donations and Charitable Fundraising</h3>
    <p className="mb-6">Contributions are voluntary. Contributions are processed by Amplify and its payment processor and are transferred to the Foundation, an independent Section 501(c)(3) organization that sponsors (that is, legally maintains) charitable funds. This is a technical tax-law usage of "sponsoring organization" and is unrelated to the Sponsor of the Prize Drawings described in Section 9, which is Amplify. A Contribution becomes a completed, irrevocable contribution to the Foundation when it is transferred to and received by the Foundation. How Amplify processes and transfers your Contribution to the Foundation, and how the Foundation applies it, including prize cost reimbursement, Amplify's platform fee, administrative expenses, and the net amount granted to Supported Organizations, is described in Section 11.</p>
    <p className="mb-6">Each month, Amplify tallies the votes cast by your Tier's members, as described in Section 8, and, acting as a professional fundraiser providing services to the Foundation, submits its own recommended allocation of your Tier's pooled Contributions across the Supported Organizations, in proportion to those tallied votes. Amplify is the sole party that formulates and submits that recommendation. As required for the charitable funds the Foundation maintains, the Foundation has exclusive legal control over all Contributions and sole discretion over all grants, and may accept, modify, or decline Amplify's recommendation, including as to any organization that does not pass the Foundation's validation procedures.</p>
    <p className="mb-6"><strong>Tax treatment.</strong> The federal and state tax treatment of a Contribution, and the deductible amount if any, are determined under applicable tax law and will be reflected in the Foundation's contribution acknowledgment. Amplify does not determine deductibility. Entrants who enter through the AMOE make no payment and therefore make no charitable contribution. Amplify does not provide tax advice and makes no representation regarding the deductibility of any Contribution. You should consult your own tax professional. Individual circumstances vary.</p>
    <p className="mb-6">Amplify is compensated by the Foundation for its role in this program, as described in Section 11.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">11 &nbsp;&nbsp; Payments, Fees, Taxes, and Cost Disclosures</h3>
    <p className="mb-6">By providing a payment method and enrolling in a Circle, you authorize Amplify, through the Services and its payment processor, to charge your first Contribution at signup and to charge recurring monthly Contributions once your Circle fills, until you cancel as permitted in Section 13 through the account section of the Services. Amplify is the merchant of record for Contribution charges and, together with its payment processor, is responsible for processing your payment and any related billing dispute; your Contribution is then transferred to the Foundation using Stripe Connect. The Foundation receives the transferred funds, has exclusive legal control over them, and issues your contribution receipt. You represent that you are authorized to use the payment method provided.</p>
    <p className="mb-6">Your enrollment is an automatically renewing, continuous-service arrangement. The material terms of that arrangement, including that Contributions continue on a recurring basis until you cancel, the amount and frequency of the charges, and how to cancel, are disclosed clearly and conspicuously before you enroll, and you must give express affirmative consent to those terms. You will receive a retainable acknowledgment of those terms after you enroll. As a matter of practice, and not as a representation of a legal requirement, the Foundation also sends a receipt after each Contribution is charged. At least once every twelve (12) months you will receive a reminder stating that your enrollment continues automatically, the amount and frequency of the charges, and how to cancel. Cancellation is available through a self-service cancellation mechanism in the account section of the Services, in the same medium in which you enrolled.</p>
    <p className="mb-6">Amplify's platform fee is the compensation the Foundation pays Amplify, under Amplify's services agreement with the Foundation, for the fundraising, technology, and administrative services described in Section 2, including operating the Services, tallying votes, and submitting monthly allocation recommendations. The net amount the Foundation grants to a Supported Organization, after third-party payment processing fees, the Foundation's administration fee, Amplify's platform fee, and reimbursement of prize costs, is therefore less than the gross amount of Contributions allocated toward it. At enrollment, you may elect to separately cover the estimated payment processing fee for your Contribution; if you do, that amount is charged in addition to your Contribution, your Contribution itself is not reduced by processing fees, and your election does not change your Tier or create any additional entry. Amplify does not guarantee that any particular portion of a Contribution reaches your Supported Organization. You are responsible for all taxes associated with any prize you win. Winners may be required to complete tax documentation, and prize values may be reported to tax authorities as required by law.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">12 &nbsp;&nbsp; Fulfillment, Redemption, and Delivery of Prizes</h3>
    <p className="mb-6">Prizes are awarded and fulfilled as described in the applicable Official Rules. Prizes are paid by Amplify from its own operating funds and are reimbursed to Amplify by the Foundation as a documented fundraising expense, separate from and in addition to Amplify's platform fee described in Section 11. Prizes are never a pass-through of Contributions. Winners must satisfy all claim, verification, identity, and eligibility requirements set out in the Official Rules within the stated deadlines. Unless the Official Rules state otherwise, prizes are non-transferable. Amplify is not responsible for prizes once awarded.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">13 &nbsp;&nbsp; Refunds, Chargebacks, and Cancellation</h3>
    <p className="mb-6">A Contribution becomes an irrevocable completed charitable gift to the Foundation once it is transferred to and received by the Foundation, which Amplify does on an ongoing basis shortly after each charge. This is not a merchant return policy: Amplify does not offer refunds of Contributions. Once transferred, the funds are no longer yours and are held for charitable purposes under the Foundation's exclusive legal control. If a genuine billing error occurs, such as a duplicate charge or an incorrect amount, notify us promptly. Billing reversals, chargebacks, and corrections after transfer to the Foundation are handled under the Foundation-approved refund and error policy, applicable law, and payment-network rules. No provision of these Terms gives you a contractual right to the return of a completed charitable gift. You can stop future Contributions at any time by cancelling, as described below.</p>
    <p className="mb-6">Prize Drawing guarantees are described in Sections 7 and 9 and are not affected by cancellation of your own enrollment.</p>
    <p className="mb-6">You may cancel at any time through the self-service cancellation mechanism in the account section of the Services. Cancellation takes effect immediately as to all future charges and all future entries. If you have already been charged, that Contribution's entry remains valid for the next Prize Drawing held for your Circle and is not forfeited by cancellation. You are not entered in any Prize Drawing for a period in which you have not been charged.</p>
    <p className="mb-6">Because Contributions become irrevocable completed gifts to the Foundation upon transfer, as described above, you agree to contact us to resolve any billing concern before initiating a chargeback or payment dispute. This gives us the opportunity to correct any billing error directly. This section does not limit any right you have under applicable law or your card issuer's rules to dispute a charge; it asks that you give us a chance to resolve the concern first. Fraudulent or bad-faith chargebacks, meaning a dispute of a Contribution you authorized and received the described entry for, may result in suspension or termination of your account and collection of amounts owed.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">14 &nbsp;&nbsp; User Content</h3>
    <p className="mb-6">The Services may allow you to submit content, including messages, comments, and other materials ("User Content"). You retain ownership of your User Content, but you grant Amplify a worldwide, non-exclusive, royalty-free, fully paid, sublicensable, and transferable license to host, store, use, reproduce, modify for formatting, publish, and display your User Content in connection with operating and promoting the Services. You represent and warrant that you own or have all necessary rights to your User Content and that it does not violate any law or infringe or misappropriate any third-party right. We may remove or refuse to display any User Content at our discretion.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">15 &nbsp;&nbsp; Publicity</h3>
    <p className="mb-6">Except for disclosures required by law or the Official Rules, Amplify will not use a winner's photograph, likeness, voice, testimonial, or similar publicity rights for advertising without the winner's separate affirmative consent. Refusal to provide such consent will not affect eligibility for or payment of a Prize.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">16 &nbsp;&nbsp; Intellectual Property</h3>
    <p className="mb-6">The Services and all associated content, text, graphics, logos, trademarks, service marks, images, audio, video, data compilations, and software are owned by Amplify or its licensors and are protected by United States and international intellectual property laws. Subject to your compliance with these Terms, Amplify grants you a limited, revocable, non-exclusive, non-transferable, non-sublicensable license to access and use the Services for their intended personal, non-commercial purpose. You may not copy, modify, distribute, sell, lease, reverse engineer, or create derivative works from the Services except as expressly permitted. All rights not expressly granted are reserved.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">17 &nbsp;&nbsp; Prohibited Conduct</h3>
    <p className="mb-6">You agree that you will not: (a) violate any applicable law or regulation; (b) use bots, scripts, or other automated means to access the Services or enter drawings except as expressly permitted by the Official Rules; (c) tamper with, disrupt, or attempt to gain unauthorized access to the Services or any drawing; (d) create multiple, false, or fraudulent accounts, or enter a drawing other than as permitted; (e) infringe or misappropriate any intellectual property or privacy right; (f) harvest or scrape data; (g) upload malware or harmful code; (h) impersonate any person or entity; or (i) interfere with the integrity, security, or proper functioning of the Services or any drawing.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">18 &nbsp;&nbsp; Electronic Communications and Email</h3>
    <p className="mb-6">By using the Services, you consent to receive communications from us electronically, including by email and through the Services, and you agree that all agreements, notices, disclosures, and other communications we provide electronically satisfy any legal requirement that such communications be in writing, consistent with the federal Electronic Signatures in Global and National Commerce Act (E-SIGN Act). Commercial email messages will comply with the CAN-SPAM Act and will include a functioning mechanism to unsubscribe. Transactional messages relating to your account and Contributions are part of the Services, and you may continue to receive them while your account is active.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">19 &nbsp;&nbsp; SMS/Text Messaging</h3>
    <p className="mb-6">If you opt in to receive text messages, you consent to receive recurring automated marketing and transactional text messages from or on behalf of Amplify at the mobile number you provide, consistent with the Telephone Consumer Protection Act (TCPA). Consent to marketing texts is not a condition of making any Contribution or entering any drawing. Message frequency varies. Message and data rates may apply. Reply STOP to cancel and HELP for help. We may suspend or terminate text messaging at any time.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">20 &nbsp;&nbsp; Third-Party Links and Services</h3>
    <p className="mb-6">The Services may contain links to, or interoperate with, third-party websites, products, and services, including the Foundation and our payment processor. We do not control and are not responsible for third-party content, policies, or practices. Your access to and dealings with any third party, including the Foundation and payment processor, are solely between you and that third party, and may be subject to that third party's own terms and privacy practices. The inclusion of any link does not imply endorsement.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">21 &nbsp;&nbsp; Monitoring, Enforcement, Suspension, and Termination</h3>
    <p className="mb-6">We may, but are not obligated to, monitor use of the Services and User Content. We may investigate suspected violations and cooperate with law enforcement. We may suspend, restrict, or terminate your access to all or part of the Services at any time, with or without notice, for any reason, including suspected violation of these Terms or the Official Rules, suspected fraud, or to comply with law. Suspension or termination of an account does not invalidate an otherwise eligible entry already earned in a commenced Drawing, revoke a completed charitable gift, or alter any Prize right governed by the applicable Official Rules; Amplify may disqualify a specific entry only on a ground expressly stated in the fixed Official Rules applicable to that Drawing. Upon termination, the rights granted to you cease, and Sections that by their nature should survive (including Sections 13 through 16 and 22 through 30) will survive.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">22 &nbsp;&nbsp; Disclaimer of Warranties</h3>
    <p className="mb-6 uppercase font-bold text-sm tracking-wide text-slate-700">
      The Services are provided "as is" and "as available" without warranties of any kind, whether express, implied, or statutory. To the fullest extent permitted by law, Amplify disclaims all implied warranties, including implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. Amplify does not warrant that the Services will be uninterrupted, secure, error-free, or free of harmful components, or that any defect will be corrected. No advice or information, whether oral or written, obtained from Amplify creates any warranty not expressly stated here. Some jurisdictions do not allow the exclusion of certain warranties, so some of these exclusions may not apply to you.
    </p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">23 &nbsp;&nbsp; Limitation of Liability</h3>
    <p className="mb-6 uppercase font-bold text-sm tracking-wide text-slate-700">
      To the fullest extent permitted by law, in no event will Amplify or its affiliates, or their respective officers, managers, members, employees, or agents, be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, data, goodwill, or other intangible losses, arising out of or relating to the Services, whether based in contract, tort (including negligence), strict liability, or any other theory, even if advised of the possibility of such damages.
    </p>
    <p className="mb-6 uppercase font-bold text-sm tracking-wide text-slate-700">
      For claims arising from or relating to Contributions you actually paid, Amplify's total aggregate liability will not exceed the total amount of Contributions you actually paid to or through Amplify in the twelve (12) months immediately preceding the event giving rise to the claim. For all other claims, Amplify's total aggregate liability will not exceed one hundred dollars ($100). For claims specifically relating to your participation in a Prize Drawing, the limitation in the Master Rules controls; this section governs all other claims.
    </p>
    <p className="mb-6">Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law, including liability for gross negligence, willful misconduct, or fraud. Some jurisdictions do not allow certain limitations, so some of the above may not apply to you. These limitations are a fundamental basis of the bargain between you and Amplify.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">24 &nbsp;&nbsp; Indemnification</h3>
    <p className="mb-6">You agree to defend, indemnify, and hold harmless Amplify and its affiliates, and their respective officers, managers, members, employees, and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) your access to or use of the Services; (b) your User Content; (c) your violation of these Terms or the Official Rules; or (d) your violation of any law or any third-party right. Amplify reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which case you agree to cooperate.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">25 &nbsp;&nbsp; Release of Claims</h3>
    <p className="mb-6">To the fullest extent permitted by law, you release and discharge Amplify and its affiliates from claims, demands, and damages of every kind arising out of or connected with disputes between you and other users or third parties, or with your participation in any Prize Drawing, except to the extent caused by Amplify's gross negligence, willful misconduct, or fraud.</p>
    <p className="mb-6">If you are a resident of California, you expressly waive California Civil Code Section 1542, which states: "A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party." You waive all rights under any other statute or common law principle of similar effect in any jurisdiction.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">26 &nbsp;&nbsp; Governing Law and Dispute Resolution</h3>
    <p className="mb-6">These Terms, and any dispute arising out of or relating to these Terms or the Services, are governed by the laws of the State of Florida, without regard to its conflict-of-laws principles, except that the Federal Arbitration Act governs the interpretation and enforcement of the arbitration provisions below.</p>
    <ul className="list-disc pl-6 space-y-4 mb-6">
      <li className="pl-2"><strong>(a) Informal Resolution.</strong> Before starting an arbitration or filing any claim, you agree to first contact us in writing at the address in Section 31 and to attempt in good faith to resolve the dispute informally for at least sixty (60) days after notice. The notice must describe the dispute and the relief sought.</li>
      <li className="pl-2"><strong>(b) Binding Individual Arbitration.</strong> If the dispute is not resolved within sixty (60) days, either party may elect to resolve it by final and binding individual arbitration administered by the American Arbitration Association (AAA) under its Consumer Arbitration Rules then in effect. The arbitration will be seated in Florida, and judgment on the award may be entered in any court of competent jurisdiction. The arbitrator has exclusive authority to resolve threshold questions of arbitrability, except that a court decides whether the Class Action Waiver in subsection (d) is enforceable.</li>
      <li className="pl-2"><strong>(c) Exceptions.</strong> Either party may bring an individual claim in small claims court if it qualifies, and either party may seek injunctive or equitable relief in court to protect intellectual property or confidential information.</li>
      <li className="pl-2"><strong>(d) Class Action Waiver.</strong> You and Amplify agree that each may bring claims against the other only in an individual capacity, and not as a plaintiff or class member in any purported class, collective, consolidated, or representative proceeding. The arbitrator may not consolidate more than one person's claims or preside over any form of class or representative proceeding. Notwithstanding the foregoing, this waiver does not extend to a claim for public injunctive relief, meaning relief that primarily benefits the public rather than the individual claimant; any such claim may be brought and resolved in court, and will be stayed pending arbitration of any remaining individual claims. If a court finds any part of this Class Action Waiver unenforceable as to a particular claim, that claim (and only that claim) must be brought in court, and the rest of this arbitration provision remains in effect for all other claims.</li>
      <li className="pl-2"><strong>(e) Mass Arbitration.</strong> If twenty-five (25) or more demands for arbitration of a similar nature are filed by or with the assistance or coordination of the same counsel or organization, the demands will be treated as a mass arbitration, batched into staged proceedings, and resolved using bellwether procedures, with the timing of fees adjusted accordingly. All claimants' applicable statutes of limitations are tolled from the date their demand is filed until their claim is resolved or removed from batching. Any claimant may opt out of the batching and bellwether process and proceed with an individually filed arbitration. Batching may not extend the resolution of any individual claim beyond twelve (12) months from filing without that claimant's consent.</li>
      <li className="pl-2"><strong>(f) Thirty-Day Right to Opt Out.</strong> You may opt out of the arbitration provisions (subsections (b), (d), and (e)) by sending written notice of your decision to opt out within thirty (30) days after you first accept these Terms to: Amplify Give LLC, Attn: Arbitration Opt-Out, 7901 4th St N, Ste 32498, St. Petersburg, FL 33702. The notice must include your name, address, and a clear statement that you wish to opt out of arbitration. If you opt out, the litigation venue in subsection (g) applies. Opting out does not affect any other part of these Terms.</li>
      <li className="pl-2"><strong>(g) Exclusive Venue for Litigation.</strong> To the extent the arbitration provisions do not apply, or for purposes of enforcing an arbitration award, you and Amplify agree that any litigation will be brought exclusively in the state or federal courts located in Pinellas County, Florida (or the corresponding federal district court), and you consent to the personal jurisdiction of those courts.</li>
      <li className="pl-2"><strong>(h) Time to File.</strong> Except where a shorter period would be void under Florida law, any claim arising out of or relating to these Terms or the Services must be brought within the period allowed by the applicable Florida statute of limitations. (Note: Florida law, at Fla. Stat. § 95.03, voids any contractual attempt to shorten the statutory limitations period, so no shortened contractual deadline is imposed here.)</li>
    </ul>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">27 &nbsp;&nbsp; California Consumer Notice</h3>
    <p className="mb-6"><strong>California Users.</strong> Under California Civil Code Section 1789.3, California users are entitled to the following consumer rights notice: You may contact us at the address in Section 31. The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by telephone at (800) 952-5210.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">28 &nbsp;&nbsp; DMCA and Intellectual Property Notices</h3>
    <p className="mb-6">Amplify respects intellectual property rights and responds to notices of alleged infringement under the Digital Millennium Copyright Act (DMCA). If you believe content on the Services infringes your copyright, send a written notice containing the information required by 17 U.S.C. Section 512(c)(3) to our designated agent at:</p>
    <p className="mb-6">
      DMCA Agent<br />
      Amplify Give LLC<br />
      7901 4th St N, Ste 32498<br />
      St. Petersburg, FL 33702<br />
      Phone: (727) 606-9509<br />
      Email: DMCA@amplifygive.com
    </p>
    <p className="mb-6">A notice must include your physical or electronic signature; identification of the copyrighted work; identification of the material claimed to be infringing and its location; your contact information; a statement of good-faith belief that the use is not authorized; and a statement, under penalty of perjury, that the information is accurate and that you are authorized to act. We may remove infringing material and terminate the accounts of repeat infringers.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">29 &nbsp;&nbsp; Changes to These Terms</h3>
    <p className="mb-6">We may modify these Terms at any time. If we make material changes, we will provide notice by posting the updated Terms with a new effective date and, where appropriate, by other reasonable means such as email or an in-Service notice. Material changes to recurring payment terms will receive any notice and renewed consent required by applicable law; changes never modify a commenced Drawing. Changes are effective when posted unless otherwise stated. Your continued use of the Services after changes take effect constitutes your acceptance of the updated Terms. If you do not agree to the updated Terms, you must stop using the Services.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">30 &nbsp;&nbsp; Miscellaneous</h3>
    <p className="mb-6">These Terms, the Privacy Policy, and the applicable Official Rules constitute the entire agreement between you and Amplify regarding the Services and supersede all prior agreements on that subject. If any provision is held invalid or unenforceable, that provision will be limited or severed to the minimum extent necessary, and the remaining provisions will remain in full force. Our failure to enforce any provision is not a waiver. You may not assign or transfer these Terms without our prior written consent; we may assign these Terms freely. There are no third-party beneficiaries except as expressly stated. Headings are for convenience only. The words "including" and "include" mean "including without limitation." Notices to you may be provided through the Services or by email.</p>

    <h3 className="text-lg md:text-xl font-bold text-slate-900 mt-12 md:mt-16 mb-4 tracking-tight">31 &nbsp;&nbsp; Contact Information</h3>
    <p className="mb-6">
      Amplify Give LLC<br />
      7901 4th St N, Ste 32498<br />
      St. Petersburg, FL 33702<br />
      Phone: (727) 606-9509<br />
      Email: legal@amplifygive.com
    </p>
  </>
);

export default TermsContent;
